// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus():Promise<string>;

export function SendPrompt(arg1:string):Promise<string>;
